@startuml "Diagrama de Sequência - Cliente"
autonumber

skinparam actorStyle awesome
skinparam monochrome false
skinparam shadowing true
skinparam defaultFontName "Segoe UI"
skinparam BoxPadding 25
skinparam ParticipantPadding 20

skinparam actor {
    BackgroundColor #E0F2FE
    BorderColor #0284C7
}
skinparam ArrowColor #334155
skinparam Note {
    BackgroundColor #FEF3C7
    BorderColor #F59E0B
    FontColor #92400E
}

actor "Cliente" as cli

box "Módulo de Acesso" #F8FAFC
    participant "Autenticação & Usuários" as mod_auth #0EA5E9
end box

box "Módulo de Atendimento" #F0FDF4
    participant "Agendamento & Agenda" as mod_agenda #22C55E
end box

box "Módulo de Oficina" #FFFBEB
    participant "Orçamentos & Serviços" as mod_os #F59E0B
end box

== Autenticação ==
cli -> mod_auth : realizarCadastro(dadosPessoais)
activate mod_auth
mod_auth --> cli : confirmação(201 Created)
deactivate mod_auth

cli -> mod_auth : login(credentials)
activate mod_auth
mod_auth --> cli : JWT Token
deactivate mod_auth

== Atendimento ==
cli -> mod_agenda : solicitarAgendamento(veiculo, dataHora)
activate mod_agenda
note over mod_agenda: **Validar:**\n- Disponibilidade\n- Vínculo Veículo
mod_agenda --> cli : agendamento(Status: PENDENTE)
deactivate mod_agenda

==  Orçamentação ==
cli -> mod_os : aprovarOrcamento(idOrcamento)
activate mod_os
mod_os --> cli : OS Criada com Sucesso
deactivate mod_os
@enduml